# Generated by Django 5.2.4 on 2025-08-08 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeadUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_unit', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.CharField(max_length=255)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_utilized', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters_features.curriculumoffering')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetGAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.CharField(max_length=255)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_utilized', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters_features.curriculumoffering')),
            ],
        ),
        migrations.CreateModel(
            name='IEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('video', 'Video'), ('brochure', 'Brochure'), ('pamphlet', 'Pamphlet'), ('ebook', 'E-Book'), ('poster', 'Poster'), ('infographic', 'Infographic'), ('manual', 'Manual'), ('others', 'Others')], max_length=50)),
                ('project_number', models.CharField(max_length=100)),
                ('sustainable_dev_goal', models.CharField(max_length=100)),
                ('thematic_area', models.CharField(choices=[('A', 'Agri-Fisheries and Food Security'), ('B', 'Biodiversity and Environmental Conservation'), ('C', 'Smart Engineering, ICT and Industrial Competitiveness'), ('D', 'Public Health and Welfare'), ('E', 'Societal Development and Equality')], max_length=1)),
                ('total_recipients', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum_offering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters_features.curriculumoffering')),
                ('lead_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters_features.leadunit')),
            ],
        ),
        migrations.CreateModel(
            name='IECRecipientsByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('farmer', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fisherfolk', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ag_technician', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('govt_employee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('private_employee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('other', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('iec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_by_category', to='adopters_features.iec')),
            ],
        ),
        migrations.CreateModel(
            name='IECRecipientsBySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('female', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('iec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_by_sex', to='adopters_features.iec')),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Farmer', 'Farmer'), ('Fisherfolk', 'Fisherfolk'), ('Government Employee', 'Government Employee'), ('Private Employee', 'Private Employee'), ('Organization', 'Organization'), ('Others', 'Others')], max_length=50)),
                ('projects_involved', models.TextField()),
                ('trainings_attended', models.TextField()),
                ('other_assistance', models.TextField()),
                ('adoption_date', models.DateField()),
                ('technologies_adopted', models.TextField()),
                ('income_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_difference', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('significant_changes', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum_offering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters_features.curriculumoffering')),
                ('lead_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters_features.leadunit')),
            ],
        ),
    ]
