# Generated by Django 5.2.4 on 2025-08-22 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table5Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('related_curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('adopter_name', models.CharField(max_length=255)),
                ('adopter_address', models.TextField(blank=True, null=True)),
                ('adopter_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('adopter_sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('adopter_category', models.CharField(blank=True, choices=[('Student', 'Student'), ('Farmer', 'Farmer'), ('Fisherfolk', 'Fisherfolk'), ('Government Employee', 'Government Employee'), ('Private Employee', 'Private Employee'), ('Organization', 'Organization'), ('Others', 'Others')], max_length=50, null=True)),
                ('projects_involved', models.TextField(blank=True, null=True)),
                ('trainings_attended', models.TextField(blank=True, null=True)),
                ('other_assistance_received', models.TextField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('technologies_adopted', models.TextField(blank=True, null=True)),
                ('monthly_income_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_income_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_significant_changes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_email', models.CharField(blank=True, max_length=255, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table5_data', to='adopters_features.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Table6IEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('related_curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('male_recipients', models.IntegerField(blank=True, null=True)),
                ('female_recipients', models.IntegerField(blank=True, null=True)),
                ('student_recipients', models.IntegerField(blank=True, null=True)),
                ('farmer_recipients', models.IntegerField(blank=True, null=True)),
                ('fisherfolk_recipients', models.IntegerField(blank=True, null=True)),
                ('ag_technician_recipients', models.IntegerField(blank=True, null=True)),
                ('gov_employee_recipients', models.IntegerField(blank=True, null=True)),
                ('private_employee_recipients', models.IntegerField(blank=True, null=True)),
                ('others_recipients', models.IntegerField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(blank=True, null=True)),
                ('project_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sdg', models.CharField(blank=True, max_length=255, null=True)),
                ('thematic_area', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_email', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='iec_documents/')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table6_data', to='adopters_features.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Table7aBudgetGAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('department', models.CharField(max_length=255)),
                ('curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_utilized', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='budget_gaa_documents/')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table7a_data', to='adopters_features.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Table7bBudgetIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('department', models.CharField(max_length=255)),
                ('curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_utilized', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='budget_income_documents/')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table7b_data', to='adopters_features.submission')),
            ],
        ),
    ]
