# Generated by Django 5.2.4 on 2025-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters_features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table6iec',
            old_name='others_recipients',
            new_name='other_recipients',
        ),
        migrations.RenameField(
            model_name='table6iec',
            old_name='private_employee_recipients',
            new_name='priv_employee_recipients',
        ),
        migrations.AddField(
            model_name='table7abudgetgaa',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table7bbudgetincome',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
