# Generated by Django 5.2.4 on 2025-08-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table5Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('related_curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('adopter_name', models.CharField(max_length=255)),
                ('adopter_address', models.TextField(blank=True, null=True)),
                ('adopter_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('adopter_sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('adopter_category', models.CharField(blank=True, choices=[('Student', 'Student'), ('Farmer', 'Farmer'), ('Fisherfolk', 'Fisherfolk'), ('Government Employee', 'Government Employee'), ('Private Employee', 'Private Employee'), ('Organization', 'Organization'), ('Others', 'Others')], max_length=50, null=True)),
                ('projects_involved', models.TextField(blank=True, null=True)),
                ('trainings_attended', models.TextField(blank=True, null=True)),
                ('other_assistance_received', models.TextField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('technologies_adopted', models.TextField(blank=True, null=True)),
                ('monthly_income_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_income_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_significant_changes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table6IEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('related_curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('male_recipients', models.IntegerField(blank=True, null=True)),
                ('female_recipients', models.IntegerField(blank=True, null=True)),
                ('student_recipients', models.IntegerField(blank=True, null=True)),
                ('farmer_recipients', models.IntegerField(blank=True, null=True)),
                ('fisherfolk_recipients', models.IntegerField(blank=True, null=True)),
                ('ag_technician_recipients', models.IntegerField(blank=True, null=True)),
                ('gov_employee_recipients', models.IntegerField(blank=True, null=True)),
                ('private_employee_recipients', models.IntegerField(blank=True, null=True)),
                ('others_recipients', models.IntegerField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(blank=True, null=True)),
                ('project_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sdg', models.CharField(blank=True, max_length=255, null=True)),
                ('thematic_area', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table7aBudgetGAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('department', models.CharField(max_length=255)),
                ('curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_utilized', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table7bBudgetIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('department', models.CharField(max_length=255)),
                ('curricular_offering', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_utilized', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetgaa',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budgetgaa',
            name='curriculum_offering',
        ),
        migrations.RemoveField(
            model_name='budgetincome',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budgetincome',
            name='curriculum_offering',
        ),
        migrations.RemoveField(
            model_name='iec',
            name='curriculum_offering',
        ),
        migrations.RemoveField(
            model_name='iec',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='iec',
            name='lead_unit',
        ),
        migrations.RemoveField(
            model_name='iecrecipientsbysex',
            name='iec',
        ),
        migrations.RemoveField(
            model_name='iecrecipientsbycategory',
            name='iec',
        ),
        migrations.DeleteModel(
            name='Adopter',
        ),
        migrations.DeleteModel(
            name='BudgetGAA',
        ),
        migrations.DeleteModel(
            name='BudgetIncome',
        ),
        migrations.DeleteModel(
            name='CurriculumOffering',
        ),
        migrations.DeleteModel(
            name='LeadUnit',
        ),
        migrations.DeleteModel(
            name='IECRecipientsBySex',
        ),
        migrations.DeleteModel(
            name='IEC',
        ),
        migrations.DeleteModel(
            name='IECRecipientsByCategory',
        ),
    ]
