# Generated by Django 5.2.4 on 2025-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters_features', '0002_rename_others_recipients_table6iec_other_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table5adopter',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='adopter_documents/'),
        ),
        migrations.AlterField(
            model_name='table6iec',
            name='thematic_area',
            field=models.CharField(blank=True, choices=[('A', 'A - Agri-Fisheries and Food Security'), ('B', 'B - Biodiversity and Environmental Conservation'), ('C', 'C - Smart Engineering, ICT and Industrial Competitiveness'), ('D', 'D - Public Health and Welfare'), ('E', 'E - Societal Development and Equality')], max_length=255, null=True),
        ),
    ]
