# Generated by Django 5.2.4 on 2025-08-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters_features', '0002_table5adopter_table6iec_table7abudgetgaa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='table5adopter',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table5_data', to='adopters_features.submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table6iec',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table6_data', to='adopters_features.submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table7abudgetgaa',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table7a_data', to='adopters_features.submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table7bbudgetincome',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table7b_data', to='adopters_features.submission'),
            preserve_default=False,
        ),
    ]
