# Generated by Django 5.2.4 on 2025-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters_features', '0003_submission_table5adopter_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table6iec',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='iec_documents/'),
        ),
        migrations.AddField(
            model_name='table7abudgetgaa',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='budget_gaa_documents/'),
        ),
        migrations.AddField(
            model_name='table7bbudgetincome',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='budget_income_documents/'),
        ),
    ]
