# Generated by Django 5.2.4 on 2025-08-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopters_features', '0004_table6iec_supporting_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table5adopter',
            name='lead_unit',
        ),
        migrations.RemoveField(
            model_name='table6iec',
            name='lead_unit',
        ),
    ]
