# Generated by Django 5.2.4 on 2025-07-29 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionPPA',
            fields=[
                ('extension_ppa_id', models.AutoField(primary_key=True, serialize=False)),
                ('ppa_name', models.CharField(max_length=500, verbose_name='PPA Title')),
            ],
            options={
                'verbose_name': 'Extension PPA',
                'verbose_name_plural': 'Extension PPAs',
                'db_table': 'tblExtensionPPA',
            },
        ),
        migrations.CreateModel(
            name='MediaOutlet',
            fields=[
                ('media_outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_outlet_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('PRINT', 'Print Media'), ('RADIO', 'Radio'), ('TV', 'Television'), ('ONLINE', 'Online/Website'), ('SOCIAL', 'Social Media')], max_length=50)),
            ],
            options={
                'db_table': 'tblMediaOutlet',
                'ordering': ['media_outlet_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionPPAFeatured',
            fields=[
                ('extension_ppa_featured_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_featured', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('extension_ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='media_features.extensionppa')),
                ('media_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_ppas', to='media_features.mediaoutlet')),
            ],
            options={
                'verbose_name': 'PPA Media Feature',
                'verbose_name_plural': 'PPA Media Features',
                'db_table': 'tblExtensionPPAFeatured',
                'ordering': ['-date_featured'],
            },
        ),
    ]
