# Generated by Django 5.2.4 on 2025-08-24 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblDepartment',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionPPA',
            fields=[
                ('extension_ppa_id', models.AutoField(primary_key=True, serialize=False)),
                ('ppa_name', models.CharField(max_length=500, verbose_name='PPA Title')),
            ],
            options={
                'verbose_name': 'Extension PPA',
                'verbose_name_plural': 'Extension PPAs',
                'db_table': 'tblExtensionPPA',
            },
        ),
        migrations.CreateModel(
            name='MediaOutlet',
            fields=[
                ('media_outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_outlet_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('PRINT', 'Print Media'), ('RADIO', 'Radio'), ('TV', 'Television'), ('ONLINE', 'Online/Website'), ('SOCIAL', 'Social Media')], max_length=50)),
            ],
            options={
                'db_table': 'tblMediaOutlet',
                'ordering': ['media_outlet_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(choices=[('DEPLOYED', 'Deployed through various modalities'), ('COMMERCIALIZED', 'Commercialized'), ('PRE_COMMERCIAL', 'With pre-commercialization activities')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technology Statuses',
                'db_table': 'tblTechnologyStatus',
            },
        ),
        migrations.CreateModel(
            name='CurricularOffering',
            fields=[
                ('curricular_offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('offering_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricular_offerings', to='media_features.department')),
            ],
            options={
                'db_table': 'tblCurricularOffering',
                'ordering': ['offering_name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_staff_name', models.CharField(max_length=255, verbose_name='Name of Faculty/Staff (Last, First MI.)')),
                ('academic_rank_position', models.CharField(choices=[('Instructor I', 'Instructor I'), ('Instructor II', 'Instructor II'), ('Instructor III', 'Instructor III'), ('Assistant Professor', 'Assistant Professor'), ('Assistant Professor I', 'Assistant Professor I'), ('Assistant Professor II', 'Assistant Professor II'), ('Assistant Professor III', 'Assistant Professor III'), ('Assistant Professor IV', 'Assistant Professor IV'), ('Associate Professor', 'Associate Professor'), ('Associate Professor I', 'Associate Professor I'), ('Associate Professor II', 'Associate Professor II'), ('Associate Professor III', 'Associate Professor III'), ('Associate Professor V', 'Associate Professor V'), ('Professor', 'Professor'), ('Professor VI', 'Professor VI'), ('University Professor', 'University Professor')], max_length=255, verbose_name='Academic Rank (Faculty)/ Position (Staff)')),
                ('employment_status', models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'COS'), ('JO', 'JO')], max_length=255, verbose_name='Employment Status')),
                ('avg_hours_per_week', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average number of hours engaged in Extension activities (per week)')),
                ('total_hours_per_quarter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Number of hours engaged in Extension activities for the period/quarter')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_involvement_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
            ],
            options={
                'verbose_name': 'Faculty Involvement',
                'verbose_name_plural': 'Faculty Involvement',
                'db_table': 'tblFacultyInvolvement',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('form_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form_instance_id', models.IntegerField(blank=True, null=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionPPAFeatured',
            fields=[
                ('extension_ppa_featured_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_featured', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('extension_ppa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='media_features.extensionppa')),
                ('media_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_ppas', to='media_features.mediaoutlet')),
            ],
            options={
                'verbose_name': 'PPA Media Feature',
                'verbose_name_plural': 'PPA Media Features',
                'db_table': 'tblExtensionPPAFeatured',
                'ordering': ['-date_featured'],
            },
        ),
        migrations.CreateModel(
            name='StudentExtensionInvolvement',
            fields=[
                ('student_involvement_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_students_for_period', models.IntegerField(verbose_name='Total Number of Students for the period (a)')),
                ('students_involved_in_extension', models.IntegerField(verbose_name='Number of Students involved in extension activities (b)')),
                ('percentage_students_involved', models.FloatField(editable=False, verbose_name='Percentage of Students involved (%)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('curricular_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_involvements', to='media_features.curricularoffering')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_involvements', to='media_features.department')),
            ],
            options={
                'verbose_name': 'Student Extension Involvement',
                'verbose_name_plural': 'Student Extension Involvements',
                'db_table': 'tblStudentExtensionInvolvement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_id', models.AutoField(primary_key=True, serialize=False)),
                ('technology_title', models.CharField(max_length=500, verbose_name='Technology Title')),
                ('year_developed', models.IntegerField()),
                ('technology_generator', models.CharField(max_length=255, verbose_name='Technology Generator')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='media_features.department')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'tblTechnology',
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supporting_documents/')),
                ('extension_ppa_featured', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.extensionppafeatured')),
                ('faculty_involvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.facultyinvolvement')),
                ('student_involvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.studentextensioninvolvement')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.technology')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyCurricularOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curricular_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_features.curricularoffering')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_features.technology')),
            ],
            options={
                'db_table': 'tblTechnologyCurricularOffering',
                'unique_together': {('technology', 'curricular_offering')},
            },
        ),
        migrations.AddField(
            model_name='technology',
            name='curricular_offerings',
            field=models.ManyToManyField(through='media_features.TechnologyCurricularOffering', to='media_features.curricularoffering'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_features.technologystatus'),
        ),
    ]
