# Generated by Django 5.2.4 on 2025-08-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionppafeatured',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='supporting_documents/'),
        ),
    ]
