# Generated by Django 5.2.4 on 2025-08-04 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0002_extensionppafeatured_supporting_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionppafeatured',
            name='supporting_document',
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supporting_documents/')),
                ('extension_ppa_featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.extensionppafeatured')),
            ],
        ),
    ]
