# Generated by Django 5.2.4 on 2025-08-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0003_remove_extensionppafeatured_supporting_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblDepartment',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(choices=[('COMMERCIALIZED', 'Commercialized'), ('PATENTED', 'Patented'), ('READY_FOR_COMMERCIALIZATION', 'Ready for Commercialization'), ('IN_DEVELOPMENT', 'In Development')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technology Statuses',
                'db_table': 'tblTechnologyStatus',
            },
        ),
        migrations.CreateModel(
            name='CurricularOffering',
            fields=[
                ('curricular_offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('offering_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricular_offerings', to='media_features.department')),
            ],
            options={
                'db_table': 'tblCurricularOffering',
                'ordering': ['offering_name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_id', models.AutoField(primary_key=True, serialize=False)),
                ('technology_title', models.CharField(max_length=500, verbose_name='Technology Title')),
                ('year_developed', models.IntegerField()),
                ('technology_generator', models.CharField(max_length=255, verbose_name='Technology Generator')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='media_features.department')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'tblTechnology',
            },
        ),
        migrations.CreateModel(
            name='TechnologyCurricularOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curricular_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_features.curricularoffering')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_features.technology')),
            ],
            options={
                'db_table': 'tblTechnologyCurricularOffering',
                'unique_together': {('technology', 'curricular_offering')},
            },
        ),
        migrations.AddField(
            model_name='technology',
            name='curricular_offerings',
            field=models.ManyToManyField(through='media_features.TechnologyCurricularOffering', to='media_features.curricularoffering'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_features.technologystatus'),
        ),
    ]
