# Generated by Django 5.2.4 on 2025-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0004_department_technologystatus_curricularoffering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologystatus',
            name='status_name',
            field=models.CharField(choices=[('DEPLOYED', 'Deployed through various modalities'), ('COMMERCIALIZED', 'Commercialized'), ('PRE_COMMERCIAL', 'With pre-commercialization activities')], max_length=50, unique=True),
        ),
    ]
