# Generated by Django 5.2.4 on 2025-08-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0005_alter_technologystatus_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.technology'),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='extension_ppa_featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.extensionppafeatured'),
        ),
    ]
