# Generated by Django 5.2.4 on 2025-08-12 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0007_formsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExtensionInvolvement',
            fields=[
                ('student_involvement_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_students_for_period', models.IntegerField(verbose_name='Total Number of Students for the period (a)')),
                ('students_involved_in_extension', models.IntegerField(verbose_name='Number of Students involved in extension activities (b)')),
                ('percentage_students_involved', models.FloatField(editable=False, verbose_name='Percentage of Students involved (%)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('curricular_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_involvements', to='media_features.curricularoffering')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_involvements', to='media_features.department')),
            ],
            options={
                'verbose_name': 'Student Extension Involvement',
                'verbose_name_plural': 'Student Extension Involvements',
                'db_table': 'tblStudentExtensionInvolvement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='student_involvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.studentextensioninvolvement'),
        ),
    ]
