# Generated by Django 5.2.4 on 2025-08-15 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0008_studentextensioninvolvement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_staff_name', models.CharField(max_length=255, verbose_name='Name of Faculty/Staff (Last, First MI.)')),
                ('academic_rank_position', models.CharField(choices=[('Instructor I', 'Instructor I'), ('Instructor II', 'Instructor II'), ('Instructor III', 'Instructor III'), ('Assistant Professor', 'Assistant Professor'), ('Assistant Professor I', 'Assistant Professor I'), ('Assistant Professor II', 'Assistant Professor II'), ('Assistant Professor III', 'Assistant Professor III'), ('Assistant Professor IV', 'Assistant Professor IV'), ('Associate Professor', 'Associate Professor'), ('Associate Professor I', 'Associate Professor I'), ('Associate Professor II', 'Associate Professor II'), ('Associate Professor III', 'Associate Professor III'), ('Associate Professor V', 'Associate Professor V'), ('Professor', 'Professor'), ('Professor VI', 'Professor VI'), ('University Professor', 'University Professor')], max_length=255, verbose_name='Academic Rank (Faculty)/ Position (Staff)')),
                ('employment_status', models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'COS'), ('JO', 'JO')], max_length=255, verbose_name='Employment Status')),
                ('avg_hours_per_week', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average number of hours engaged in Extension activities (per week)')),
                ('total_hours_per_quarter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Number of hours engaged in Extension activities for the period/quarter')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_involvement_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
            ],
            options={
                'verbose_name': 'Faculty Involvement',
                'verbose_name_plural': 'Faculty Involvement',
                'db_table': 'tblFacultyInvolvement',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='faculty_involvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.facultyinvolvement'),
        ),
    ]
