# Generated by Django 5.2.4 on 2025-08-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0009_facultyinvolvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='form_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
