# Generated by Django 5.2.5 on 2025-08-18 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0011_supportingdocument_submitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherActivities',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_conducted', models.DateField()),
                ('activity_title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('TRAINING', 'Training'), ('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('OUTREACH', 'Community Outreach'), ('OTHER', 'Other')], max_length=50)),
                ('participants', models.CharField(max_length=255, verbose_name='Number/Type of Participants')),
                ('purpose', models.TextField()),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source_of_funds', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tblOtherActivities',
                'ordering': ['-date_conducted'],
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_received_award', models.CharField(max_length=255)),
                ('award_title', models.CharField(max_length=500)),
                ('award_donor', models.CharField(max_length=255)),
                ('level_of_award', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], max_length=50)),
                ('date_received', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='media_features.department')),
            ],
            options={
                'db_table': 'tblAwards',
                'ordering': ['-date_received'],
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.awards'),
        ),
        migrations.CreateModel(
            name='ImpactAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('proponent_ias', models.CharField(max_length=255, verbose_name='Proponent/IAs')),
                ('date_conducted', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('curricular_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessments', to='media_features.curricularoffering')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessments', to='media_features.department')),
                ('extension_ppa_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessments', to='media_features.extensionppa')),
            ],
            options={
                'db_table': 'tblImpactAssessment',
                'ordering': ['-date_conducted'],
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='impact_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.impactassessment'),
        ),
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('ordinance_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordinance_title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('circular_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordinances', to='media_features.curricularoffering')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinances', to='media_features.department')),
                ('extension_ppa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordinances', to='media_features.extensionppa')),
            ],
            options={
                'db_table': 'tblOrdinance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='ordinance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.ordinance'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='other_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='media_features.otheractivities'),
        ),
    ]
