# Generated by Django 5.2.4 on 2025-08-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0012_category_collaboratingagency_leadunit_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name'], 'verbose_name': 'Lead Unit Department/Unit', 'verbose_name_plural': 'Lead Unit Departments/Units'},
        ),
        migrations.AddField(
            model_name='department',
            name='lead_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_features.leadunit', verbose_name='Lead Unit'),
        ),
    ]
