# Generated by Django 5.2.5 on 2025-08-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0012_otheractivities_awards_supportingdocument_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinance',
            name='curricular_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordinances', to='media_features.curricularoffering'),
        ),
    ]
