# Generated by Django 5.2.5 on 2025-08-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0013_remove_ordinance_circular_offering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinance',
            name='circular_offering',
        ),
    ]
