# Generated by Django 5.2.4 on 2025-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0013_alter_department_options_department_lead_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='training_documents/', verbose_name='Supporting Document'),
        ),
    ]
