# Generated by Django 5.2.5 on 2025-08-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0014_remove_ordinance_circular_offering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordinance',
            options={'ordering': ['-date_approved']},
        ),
        migrations.RemoveField(
            model_name='awards',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='impactassessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordinance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otheractivities',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='otheractivities',
            name='participants',
            field=models.CharField(max_length=255, verbose_name='Number/Type of Partipants'),
        ),
    ]
