# Generated by Django 5.2.4 on 2025-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0014_training_supporting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='TotalNoOfPersonsTrained',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
