# Generated by Django 5.2.4 on 2025-08-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_features', '0015_alter_training_totalnoofpersonstrained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='TrainingNo',
        ),
        migrations.AddField(
            model_name='training',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='Number_of_days_trained',
            field=models.CharField(choices=[('5+', '5 or more days (x 2.00)'), ('3-4', '3 to 4 days (x 1.5)'), ('2', '2 days (x 1.25)'), ('1', '1 day (8 hours) (x 1.00)'), ('less_1', 'Less than 1 day or 8 hours (x 0.5)')], max_length=20, verbose_name='Number of days trained'),
        ),
    ]
