# Generated by Django 5.2.4 on 2025-08-24 02:18

import django.db.models.deletion
import partnerships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvSClients',
            fields=[
                ('adsclients_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('categ', models.TextField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'advsclients',
            },
        ),
        migrations.CreateModel(
            name='AsOverallRating',
            fields=[
                ('oallrate_id', models.AutoField(primary_key=True, serialize=False)),
                ('one', models.IntegerField(blank=True, null=True)),
                ('two', models.IntegerField(blank=True, null=True)),
                ('three', models.IntegerField(blank=True, null=True)),
                ('four', models.IntegerField(blank=True, null=True)),
                ('five', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asoverallrating',
            },
        ),
        migrations.CreateModel(
            name='AsTimeliness',
            fields=[
                ('astimeliness_id', models.AutoField(primary_key=True, serialize=False)),
                ('one', models.IntegerField(blank=True, null=True)),
                ('two', models.IntegerField(blank=True, null=True)),
                ('three', models.IntegerField(blank=True, null=True)),
                ('four', models.IntegerField(blank=True, null=True)),
                ('five', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'astimeliness',
            },
        ),
        migrations.CreateModel(
            name='AwardRcvd',
            fields=[
                ('awardrcvd_id', models.AutoField(primary_key=True, serialize=False)),
                ('titleaward', models.TextField(blank=True, null=True)),
                ('conferagn', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'awardrcvd',
            },
        ),
        migrations.CreateModel(
            name='AwardsRcvdExter',
            fields=[
                ('arexter_id', models.AutoField(primary_key=True, serialize=False)),
                ('toaward', models.TextField(blank=True, null=True)),
                ('conferagency', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'awardsrcvdexter',
            },
        ),
        migrations.CreateModel(
            name='CmmSrvy',
            fields=[
                ('cmmsrvyid', models.AutoField(primary_key=True, serialize=False)),
                ('datecondt', models.DateField(blank=True, null=True)),
                ('dvstake', models.DateField(blank=True, null=True)),
                ('datepresent', models.DateField(blank=True, null=True)),
                ('datercvd', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cmmsrvy',
            },
        ),
        migrations.CreateModel(
            name='EstExsFund',
            fields=[
                ('estexsfund_id', models.AutoField(primary_key=True, serialize=False)),
                ('amntchcvsu', models.IntegerField(blank=True, null=True)),
                ('amntchpartagency', models.IntegerField(blank=True, null=True)),
                ('partagencyname', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'estexsfund',
            },
        ),
        migrations.CreateModel(
            name='IfpoProg',
            fields=[
                ('ifpoprogid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=190, null=True)),
                ('proglead', models.TextField(blank=True, null=True)),
                ('apprvbudg', models.IntegerField(blank=True, null=True)),
                ('cntptfund', models.IntegerField(blank=True, null=True)),
                ('totalbudg', models.IntegerField(blank=True, null=True)),
                ('incldateid', models.IntegerField(blank=True, null=True)),
                ('moanoid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ifpoprog',
            },
        ),
        migrations.CreateModel(
            name='IfpoProgExter',
            fields=[
                ('ifpoprogexter_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('proglead', models.CharField(blank=True, max_length=50, null=True)),
                ('abfundagency', models.IntegerField(blank=True, null=True)),
                ('cpfundcvsu', models.IntegerField(blank=True, null=True)),
                ('tbudget', models.IntegerField(blank=True, null=True)),
                ('incldates', models.TextField(blank=True, null=True)),
                ('moano_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ifpoprogexter',
            },
        ),
        migrations.CreateModel(
            name='LeadUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('contper', models.CharField(blank=True, max_length=150, null=True)),
                ('continf', models.CharField(blank=True, max_length=175, null=True)),
            ],
            options={
                'db_table': 'leadunit',
            },
        ),
        migrations.CreateModel(
            name='PartnerAgencies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameagen', models.CharField(blank=True, max_length=150, null=True)),
                ('headagen', models.CharField(blank=True, max_length=100, null=True)),
                ('contdet', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'partneragencies',
            },
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('projid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=90, null=True)),
                ('tmbrroles', models.TextField(blank=True, null=True)),
                ('apprvbudg', models.IntegerField(blank=True, null=True)),
                ('cntptfund', models.IntegerField(blank=True, null=True)),
                ('totalbudg', models.IntegerField(blank=True, null=True)),
                ('incldateid', models.IntegerField(blank=True, null=True)),
                ('moanoid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proj',
            },
        ),
        migrations.CreateModel(
            name='ProjectNoInText',
            fields=[
                ('project_no', models.IntegerField(primary_key=True, serialize=False)),
                ('proj_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'projectnointext',
            },
        ),
        migrations.CreateModel(
            name='ProjExter',
            fields=[
                ('projexter_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('tmembers', models.TextField(blank=True, null=True)),
                ('abfundagency', models.IntegerField(blank=True, null=True)),
                ('cpfundcvsu', models.IntegerField(blank=True, null=True)),
                ('tbudget', models.IntegerField(blank=True, null=True)),
                ('incldates', models.TextField(blank=True, null=True)),
                ('moano_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projexter',
            },
        ),
        migrations.CreateModel(
            name='AdvServices',
            fields=[
                ('advservices_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('curricoff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Curriculum Offered')),
                ('adservprov', models.TextField(blank=True, null=True)),
                ('incldates', models.TextField(blank=True, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
                ('totaladservreq', models.IntegerField(blank=True, null=True)),
                ('totaladservreqrespond', models.IntegerField(blank=True, null=True)),
                ('sdgnum', models.CharField(blank=True, max_length=70, null=True)),
                ('themarea', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('clientsid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.advsclients')),
                ('adservoverall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.asoverallrating')),
                ('adservtimeliness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.astimeliness')),
                ('estexsourcefund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.estexsfund')),
                ('lunitid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.leadunit')),
                ('collabagenciesid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partneragencies')),
            ],
            options={
                'db_table': 'advservices',
            },
        ),
        migrations.CreateModel(
            name='AdvServicesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=partnerships.models.upload_to_advservices)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('advservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='partnerships.advservices')),
            ],
        ),
        migrations.CreateModel(
            name='AdvServicesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=partnerships.models.upload_to_advservices)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('advservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partnerships.advservices')),
            ],
        ),
        migrations.CreateModel(
            name='ExterFep',
            fields=[
                ('exterfep_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('categid', models.CharField(blank=True, max_length=15, null=True)),
                ('curricoffid', models.CharField(blank=True, max_length=50, null=True)),
                ('fundagency', models.CharField(blank=True, max_length=150, null=True)),
                ('dtappfagency', models.DateField(blank=True, null=True)),
                ('dtinmeet', models.DateField(blank=True, null=True)),
                ('benef', models.TextField(blank=True, null=True)),
                ('sdgnum', models.CharField(blank=True, max_length=70, null=True)),
                ('themarea', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('awardrcvdid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.awardsrcvdexter')),
                ('ifpoprogid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.ifpoprogexter')),
                ('lunitid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.leadunit')),
                ('collabgenid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partneragencies')),
            ],
            options={
                'db_table': 'exterfep',
            },
        ),
        migrations.CreateModel(
            name='ExterFepFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=partnerships.models.upload_to_exterfep)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exterfep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='partnerships.exterfep')),
            ],
        ),
        migrations.CreateModel(
            name='ExterFepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=partnerships.models.upload_to_exterfep)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exterfep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partnerships.exterfep')),
            ],
        ),
        migrations.CreateModel(
            name='InterFep',
            fields=[
                ('interfepid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('categid', models.CharField(blank=True, max_length=15, null=True)),
                ('curricoffid', models.CharField(blank=True, max_length=50, null=True)),
                ('dateapprec', models.DateField(blank=True, null=True)),
                ('dateappborid', models.DateField(blank=True, null=True)),
                ('dateincep', models.DateField(blank=True, null=True)),
                ('benef', models.TextField(blank=True, null=True)),
                ('sdgnum', models.CharField(blank=True, max_length=70, null=True)),
                ('themarea', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('awrdrcvdid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.awardrcvd')),
                ('cmmsrvyid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.cmmsrvy')),
                ('ifpartofprogid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.ifpoprog')),
                ('lunitid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.leadunit')),
                ('collabagenid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partneragencies')),
            ],
            options={
                'db_table': 'interfep',
            },
        ),
        migrations.CreateModel(
            name='InterFepFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=partnerships.models.upload_to_interfep)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('interfep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='partnerships.interfep')),
            ],
        ),
        migrations.CreateModel(
            name='InterFepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=partnerships.models.upload_to_interfep)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('interfep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partnerships.interfep')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('partship_id', models.AutoField(primary_key=True, serialize=False)),
                ('moano', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('categ', models.CharField(blank=True, max_length=100, null=True)),
                ('datenotar', models.DateField(blank=True, null=True)),
                ('curricoff', models.CharField(blank=True, max_length=100, null=True)),
                ('numpart', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('catage', models.CharField(blank=True, max_length=50, null=True)),
                ('natpart', models.CharField(blank=True, max_length=100, null=True)),
                ('tappext', models.CharField(blank=True, max_length=100, null=True)),
                ('tofpart', models.CharField(blank=True, max_length=100, null=True)),
                ('dappbor', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('incldate', models.DateField(blank=True, null=True)),
                ('amntinvlv', models.IntegerField(blank=True, null=True)),
                ('sdgnum', models.CharField(blank=True, max_length=70, null=True)),
                ('themarea', models.CharField(blank=True, max_length=30, null=True)),
                ('extacperiod', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('leadunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.leadunit')),
                ('partagency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partneragencies')),
            ],
            options={
                'db_table': 'partnership',
            },
        ),
        migrations.AddField(
            model_name='interfep',
            name='partship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partnership'),
        ),
        migrations.AddField(
            model_name='exterfep',
            name='partship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partnership'),
        ),
        migrations.AddField(
            model_name='advservices',
            name='partship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partnership'),
        ),
        migrations.CreateModel(
            name='PartnershipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=partnerships.models.upload_to_partnership)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='partnerships.partnership')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=partnerships.models.upload_to_partnership)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partnerships.partnership')),
            ],
        ),
        migrations.AddField(
            model_name='interfep',
            name='projid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.proj'),
        ),
        migrations.AddField(
            model_name='interfep',
            name='projno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.projectnointext'),
        ),
        migrations.AddField(
            model_name='exterfep',
            name='projno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.projectnointext'),
        ),
        migrations.AddField(
            model_name='advservices',
            name='projno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.projectnointext'),
        ),
        migrations.AddField(
            model_name='exterfep',
            name='projid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.projexter'),
        ),
    ]
