# Generated by Django 5.2.4 on 2025-08-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='natpart',
            field=models.CharField(blank=True, choices=[('Internal', 'Internally Funded'), ('External', 'Externally Funded'), ('Both', 'Both Internal and External'), ('Advisory', 'Advisory Services')], max_length=100, null=True),
        ),
    ]
