# Generated by Django 5.2.4 on 2025-08-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0002_alter_partnership_natpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifpoprog',
            name='incldateid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proj',
            name='incldateid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
