# Generated by Django 5.2.4 on 2025-08-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_change_incldateid_to_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exterfep',
            name='benef',
        ),
        migrations.RemoveField(
            model_name='exterfep',
            name='categid',
        ),
        migrations.RemoveField(
            model_name='interfep',
            name='benef',
        ),
        migrations.RemoveField(
            model_name='interfep',
            name='categid',
        ),
        migrations.RemoveField(
            model_name='interfep',
            name='dateapprec',
        ),
        migrations.RemoveField(
            model_name='interfep',
            name='dateincep',
        ),
        migrations.RemoveField(
            model_name='partneragencies',
            name='contdet',
        ),
        migrations.RemoveField(
            model_name='partneragencies',
            name='headagen',
        ),
    ]
